SET DEFINE OFF;
Insert into ALLOW_CAT_ALC
   (ALC_ID, ALC_NAME, ALC_DESC_TXT, ALC_CATEGORY_CD, ALC_DECIPHER_LABEL)
 Values
   (598, 'INA_ACTIVITY_COMM_METHOD', 'Case Activity Methods of Communication', 4846, NULL);
COMMIT;


=========================================================================================================

SET DEFINE OFF;
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3594, 'Y', NULL, 'US Mail', 598, 
    NULL, NULL, 0, 'US Mail', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3595, 'Y', NULL, 'Email', 598, 
    NULL, NULL, 0, 'Email', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3596, 'Y', NULL, 'Telephone', 598, 
    NULL, NULL, 0, 'Telephone', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3597, 'Y', NULL, 'Fax', 598, 
    NULL, NULL, 0, 'Fax', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3598, 'Y', NULL, 'In person', 598, 
    NULL, NULL, 0, 'In person', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3599, 'Y', NULL, 'Video Conference', 598, 
    NULL, NULL, 0, 'Video Conference', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3600, 'Y', NULL, 'Other', 598, 
    NULL, NULL, 0, 'Other', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (3601, 'Y', NULL, 'Not Applicable', 598, 
    NULL, NULL, 0, 'Not Applicable', NULL, 
    NULL, NULL);
Insert into ALLOW_VAL_ALV
   (ALV_ID, ALV_ACTIVE_IND, ALV_RELATED_CD, ALV_SHORT_DESC_TXT, FK_ALC_ID, 
    FK_ALV_ID, ALV_DECIPHER_CODE, ALV_SORT_ORDER_NBR, ALV_LONG_DESC_TXT, ALV_SP_SHORT_DESC_TXT, 
    ALV_DISPLAY_ON, ALV_CHANGE_LOG)
 Values
   (7010, 'Y', NULL, 'Electronic', 598, 
    NULL, 'Y', NULL, 'Communicated with Employer through Wage Intake Process', NULL, 
    NULL, NULL);
COMMIT;


=======================================================================================

